server:
  port: 9001

spring:
  application:
    name: product-service
  data:
    mongodb:
      database: product-service
      host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka